### ISSUE TITLE
Difference between f1tenth-gym

### ISSUE THREAD

**Issue by QingquanBao** [JZ76/f1tenth_simulator_two_agents#2]
Hi Jiacheng,

Your work is super interesting and great!! I have looked into your paper, which list the following implementations:
- Adding the second vehicle to the simulator.
• Adding a box collider.
• Adding LiDAR pattern.
• Improving vehicle model

However, after checking the f1tenth gym API, they also offer multi agents, LiDAR scans, and collision models. So I am curious what's the difference of your implementation. Thanks

**Comment by JZ76** [comment]
Hi Qingquan,

Sorry for my late reply, being on a business trip these days.

That is a great question, I noticed that there will have many same feature as the f1tenth gym before I started the development. There are two main reasons I still carried on the development, first, as you may know, the gym depends on many external modules, such as Nvidia, and will lead to performance issue of your computer (possibly also due to it is an 3D environment); secondly, since the structure of the original version code, f1tenth simulator, is rather simple to understand, which only used publisher/subscriber and some basic ROS message. It is easy to understand for a rookie on ROS and C++ :); yes, that's me.

For the details of the implementations, they are completely different from each other. Honestly, I would like to give more details of the implementation, but the size probably doesn't quite fit into this reply.

Still, thanks for the question, if you got any other questions, please just let me know!

All the best, 
Jiancheng
